# Modules de NEMO-PROJECT
# true  = module activé
# false = module désactivé

[core]
actions = true
config = true
scripts = true

[compression]
zip = true
tar = true
seven_zip = true
extract = true

[conversion]
pdf = true
webp = true
mp3 = true
mp4 = true
png = true

[images]
optimize = true
resize = true
clean_exif = true

[security]
secure_delete = true
sha256 = true
md5 = true
gpg = true

[network]
scp = false

[utilities]
bulk_rename = true
duplicate = true
