# Préférences utilisateur pour NEMO-PROJECT

[actions]
enable_zip = true
enable_tar = true
enable_7z = true
enable_pdf = true
enable_webp = true
enable_mp3 = true
enable_mp4 = true
enable_optimize = true
enable_resize = true
enable_png = true
enable_extract_audio = true
enable_secure_delete = true
enable_sha256 = true
enable_md5 = true
enable_gpg = true
enable_clean_exif = true
enable_bulk_rename = true
enable_duplicate = true
enable_scp = false   # désactivé par défaut

[system]
auto_update = false
debug_mode = false
